
[package]
name = "pallet-zksnark"
version = "0.1.0"
edition = "2021"

[lib]
name = "pallet_zksnark"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Substrate Core Dependencies
frame-support = { version = "39.0.0", default-features = false }
frame-system = { version = "39.0.0", default-features = false }
sp-runtime = { version = "40.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-io = { version = "39.0.0", default-features = false }
sp-version = { version = "37.0.0", default-features = false }
sp-core = { version = "35.0.0", default-features = false }
ark-bls12-381 = "0.5.0"
ark-std = "0.5.0"
ark-relations = "0.5.1"
ark-ff = "0.5.0"
ark-r1cs-std = "0.5.0"
hex = { version = "0.4", default-features = false, features = ["alloc"] }
[build-dependencies]
fs_extra = "1.3.0"
which = "7.0.1"

# Encoding/Decoding
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false, features = ["derive"] }
scale-info = { version = "2.11.6", default-features = false, features = ["derive"] }

# (Optional) If you're using the zk-snarks library
# zk-snarks-lib = { path = "../path/to/zk-snarks-lib", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-core/std",
    "sp-io/std",
    "sp-version/std",
    "codec/std",
    "scale-info/std",
    # "zk-snarks-lib/std",  # Uncomment if using zk-snarks-lib
]