[package]
name = "pallet-zksnark"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A Substrate pallet for zk-SNARK verification"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false, features = ["derive"] }
scale-info = { version = "2.11.6", default-features = false, features = ["derive"] }
frame-support = { version = "39.0.0", default-features = false }
frame-system = { version = "39.0.0", default-features = false }
frame-benchmarking = { version = "39.0.0", default-features = false, optional = true }
sp-core = { version = "35.0.0", default-features = false }
sp-io = { version = "39.0.0", default-features = false }
sp-runtime = { version = "40.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }

# Cryptographic dependencies
ark-bls12-381 = { version = "0.5.0", default-features = false }
ark-ec = { version = "0.5.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
ark-std = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false }
ark-groth16 = { version = "0.5.0", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0.136", default-features = false, features = ["alloc"] }

[dev-dependencies]
sp-core = { version = "35.0.0" }
sp-io = { version = "39.0.0" }
sp-runtime = { version = "40.0.0" }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "ark-bls12-381/std",
    "ark-ec/std",
    "ark-ff/std",
    "ark-std/std",
    "ark-serialize/std",
    "ark-groth16/std",
    "serde_json/std",
    "hex/std",
]
